### PR TITLE
Lua: backported bugfixes, support for binary litterals and a alternative bitwise operations library

### PR DESCRIPTION
**Pull request by goodusername123**
Hello apologies if this pull request and the included testcases seem a bit messy in their presentation however recently circumstances have come up that require me to submit this soon since my github account has the chance of being abandoned very soon, so I may not have the ability to check in on this pull request after I submit it.

here are testcases for each thing in this pull request:
[testcases.zip](https://github.com/chrisant996/clink/files/8510697/testcases.zip)

With that out of way this pull request does 3 things

**Backported Fixes from later versions of Lua:**
these are fixes that have been applied and or backported from later versions of Lua with testcases included and tested, the only test I was not able to test fully was "Dead keys with nil values can stay in weak tables" since I do not have memory checker on hand. these Fixes and the testcases for them are sourced from [here](https://www.lua.org/bugs.html) and [here](https://github.com/lua/lua)

**Support for parsing Binary Litterals:**
this adds support for Binary Litterals behind a define when compiling. without this change Lua simply errors when given binary litterals normaly. this patch is from [here](http://lua-users.org/wiki/LuaPowerPatches) (the download links on the site are very unreliable so I have attached the original patch file to this pull request)
[jh-lua-bin-5.2.1.zip](https://github.com/chrisant996/clink/files/8510702/jh-lua-bin-5.2.1.zip)

**Alternative bitwise operations library:**
this adds a optional to use lightweight bitwise operations module to Lua which can be used if "local bit = require("bit")" is used in a Lua file and does not use any or much extra memory when not defined/used in a Lua file. Documentation is available [here](https://bitop.luajit.org/api.html) however I have attached a extra commit which holds the Documentation locally in the repo if desired also bit.c and the Lua files included in the testcases are from this file [here](https://bitop.luajit.org/download/LuaBitOp-1.0.2.tar.gz) only difference is I applied a patch from [here](https://github.com/LuaJIT/LuaJIT/issues/384) that adds proper support for future Lua versions in case clink itself or anyone trying to fork clink attempts to update Lua to something after 5.2.4 and the other change is a small one where I changed a part in bit.c to be more properly aware of newer versions of MSVC which I sourced from [here](https://github.com/LuaJIT/LuaJIT/commit/3ece3a3e3a448ecc54e317fd5743d1f4c19db28b).

### CODE REVIEW

**Comment by chrisant996** [comment]
Hi, @goodusername123, and thank you for putting this together.

**Re: backported bug fixes** -- This could be interesting.  Is there a list of which fixes are included?  When taking fixes, I generally want one commit per fix, and I want descriptions of each problem being fixed.

**Re: alternative bitwise operations library** -- What is the purpose of an alternative bitwise operations library?  The library's documentation doesn't state why it exists or what problem(s) it intends to solve.  Lua 5.2 has a built-in bitwise operations library [`bit32`](https://www.lua.org/manual/5.2/manual.html#6.7), and introducing a second bitwise library seems confusing and presents additional compatibility challenges for script authors.

**Re: binary literals** -- This seems like a fun feature, but it doesn't seem very necessary or important.  It also presents (insurmountable?) compatibility challenges for script authors.  I think I have to pass on this one.

**Comment by goodusername123** [comment]
> Re: backported bug fixes -- This could be interesting. Is there a list of which fixes are included? When taking fixes, I generally want one commit per fix, and I want descriptions of each problem being fixed.

[bugfix commits.txt](https://github.com/chrisant996/clink/files/8515163/bug.list.with.fix.commits.txt) ( here is a list of each commit that each bugfix is based on (although some of them are not directly applicable when taken directly) )

There are 6 Bug Fixes in total Each of them based on or directly from their Official implementations, The only exception was a fix in the Garbage Collector for "dead keys with nil values can stay in weak tables" which has been changed in my latest commit to be the proper version Officially put in Lua along with me being able to more properly test it and see that "nil" should be printed with the testcase as opposed to nothing being printed at all.

The testcases I attached to the main pull request include a test for each specific fix and inside each test there is a comment about what behavior is fixed, however the description of what specific behavior is fixed with each isn't consistently laid out in the same manner between each file.


If you want I could try to make a new pull request that has each of the 6 Fixes separated however I'm not that good at using github (only ever used the web interface) and it might become a bit of a mess so as a current alternative here is each fix in patch/diff form:
[diff patches (Lua Fixes).zip](https://github.com/chrisant996/clink/files/8515776/diff.patches.Lua.Fixes.zip)


also apologies for the poor grammar, sentence structure and other various communication issues on my end, Text communication is very much not my strong suit.

**Comment by chrisant996** [comment]
Patch/diff with brief comment on each is a great format, thanks! Will take a look tonight.

**Comment by goodusername123** [comment]
A question I have that relates to both of the quotes I am attempting to respond to below is what do you specifically mean when you mention "compatibility challenges" is it the fear that older scripts could be broken by these changes? because if that's the case then worry should not be applied since these changes do not break pre-existing/older scripts and could only break scripts meant for older versions of clink under very very specific circumstances which would be under the realm of behavior that is very fragile and is very comparable to say making use of very specific bugs in either clink or Lua itself to function. however if you mean it in the sense that people will have trouble supporting older versions of clink such as v0.4.9 due to older versions not supporting these features then why is this not a fear for the newer clink related functions being added each version? there might a third possible meaning that I am not seeing/understanding which is very possible.

in the end these changes aren't really necessary like you said so it's not too big of a deal if they don't get accepted I just figured that they would be nice to have for people who wanted to make use of them, didn't present the problem of breaking pre-existing scripts and could easily be ported over to work in possible future situations where someone could say fork clink and port it to a newer major version of Lua or something similar for whatever purposes.

> Re: alternative bitwise operations library -- What is the purpose of an alternative bitwise operations library? The library's documentation doesn't state why it exists or what problem(s) it intends to solve. Lua 5.2 has a built-in bitwise operations library [bit32](https://www.lua.org/manual/5.2/manual.html#6.7), and introducing a second bitwise library seems confusing and presents additional compatibility challenges for script authors.

The history goes that it was made and existed before the official implementation in Lua 5.2 hence one of the reasons the one in Lua 5.2 is prefixed as "bit32" and not simply just "bit". My original intention behind including this was that is was so lightweight and that anyone who preferred or relied upon it (a example of a case would be code for a function or something else that was originally meant for Lua 5.1 or code from somewhere that was only made with "bit" and not "bit32" to keep consistent compatibility between versions of Lua from 5.1 and above and LuaJIT) could easily make use of it without having to include or create complied binaries to ship which could lead to problems. In the end this isn't really all that necessary (especially the commit including the docs in retrospect) however I figured that it won't hurt since all of it's functions are behind "local bit = require("bit")" and a small note could be made in clink's docs stating that it is supported if needed but not fully documenting and making a big deal about it's inclusion to prevent confusion.
also something it supports that the default library doesn't is "tobit" and "tohex"

> Re: binary literals -- This seems like a fun feature, but it doesn't seem very necessary or important. It also presents (insurmountable?) compatibility challenges for script authors. I think I have to pass on this one.

yeah it isn't really necessary. My original intention for including it was that it's natively supported in things such as LuaJIT and is easily portable to later versions of normal Lua (I currently am making a port of it to Lua 5.4 that's almost complete). and someone could find use in being able to directly use binary literals rather then having to manually convert them first.

**Comment by chrisant996** [comment]
**Re: compatibility challenges** -- The issue is not whether old scripts can work with the new Lua changes. The concern is the opposite case: any scripts that use or rely upon any of these Lua enhancements may fail to even load/compile when used in an older version of Clink. The changes essentially create a new "major version" of Clink that is incompatible even at the Lua syntax level (e.g. binary literals). This can also create issues with [precompiled scripts](https://www.lua.org/manual/5.2/luac.html) (the Clink repo builds a Lua precompiler, which works -- I choose to be careful not to break the Lua version in ways that break precompiled scripts).

Every time I add a new Lua API in Clink, a script that uses the new API needs to be careful when it is loaded in an older version of Clink (e.g. Cmder usually lags behind the latest version of Clink).  If I make the Lua itself have that same problem, in addition to specific API usages, then that can be even harder (and less obvious) for scripts to deal with.

So, I avoid making changes to Lua itself unless there are important reasons, and there are not ways to already accomplish the same outcome another way in Lua.

**Comment by goodusername123** [comment]
Ah I see, well then all that's needed from this pull request then is the backported Fixes so feel free to close this once they are tested and applied, also the reason they didn't make it into release Lua 5.2.4 is due to them being discovered after Lua 5.2's end of support in 2015.

**Comment by chrisant996** [comment]
I reviewed the patches, and they make sense. There are a couple things I want to understand better, and I will also verify against Lua 5.4 (to the extent that the affected code is still present in 5.4).

I'll probably include them this later this week.

**Comment by chrisant996** [comment]
I appreciate very much the effort that went into collecting these backports and etc together for consideration.

After careful consideration, I believe the best course of action for the moment is to defer applying these fixes.

1. There have been no reports of these issues being problematic yet in Clink.
2. There is no clean way to write a Lua script that takes advantage of these fixes but still works on older Clink versions.
3. Clink currently hosts Lua 5.2.4, the final official release of Lua 5.2.  That is a well known state, and I am reluctant to create a new non-official state that does not correspond to any released Lua version number.  There is value is using a well known state, even if the well known state has obscure edge case issues.

**Comment by chrisant996** [comment]
The 6 bug fixes have been applied.

One introduced a 64-bit compiler warning, but the fix is obvious.

**Pull request closed without merging**
