### PR TITLE
Update return value documentation of log.getfile

### PR DESCRIPTION
**Pull request by sebthom**

### CODE REVIEW

**Comment by chrisant996** [comment]
@sebthom Why is this change being suggested?
Are you just inspecting source code?

I believe this can only return nil inside `clink lua`, which is undocumented and unsupported.
This documentation change seems misleading and inaccurate to me.

**Comment by sebthom** [comment]
No, I actually get a nil value. Maybe this is a clink bug then?
If I load a lua script with
```lua
print("log.logfile "..tostring(log.logfile))
```
I will get this output in a new CMD window:
image

**Comment by chrisant996** [comment]
I think it's a typo in your script.

The API is `log.getfile()`.
The screenshot shows `log.logfile`, which refers to the value in a global variable by a different name, which doesn't exist.

- Using `log.logfile` refers to a field member.
- Using `log.logfile()` calls the field as a function and gets the returned value.

The script needs to be edited to replace each `logfile` with `getfile()`.
```lua
print("log.getfile() "..tostring(log.getfile()))
```

It should report a filename string.

**Comment by sebthom** [comment]
True, that was a typo, I now tried this:
```lua
function dump(o)
   if type(o) == 'table' then
      local s = '{ '
      for k,v in pairs(o) do
         if type(k) ~= 'number' then k = '"'..k..'"' end
         s = s .. '['..k..'] = ' .. dump(v) .. ','
      end
      return s .. '} '
   else
      return tostring(o)
   end
end

print(dump(log))
print("---------------------")
print("log.getfile() "..tostring(log.getfile()))
```

and still get `nil`
```
{ ["getfile"] = function: 00007FFCAAD32490,["info"] = function: 00007FFCAAD32360,}
---------------------
log.getfile() nil
```

I am using Clink v1.4.19.57e404

**Comment by chrisant996** [comment]
I made the following script:
```lua
dumpvar(log) -- Uses the dumpvar() function from luaexec.lua.
print("")
print("log file = " .. tostring(log.getfile()))
```

The I reloaded via `Ctrl-X`,`Ctrl-R`:
image

Oh, maybe you are using `clink inject --nolog`?

**Comment by sebthom** [comment]
Yes, I was apparently using `--nolog`! I totally forgot about setting it many moons ago...

**Pull request merged**
