### PR TITLE
Fix for Windows insider build 20246

### PR DESCRIPTION
**Pull request by nikitalita**
Remove restriction on hitting other functions,
increase search size to 135 bytes.

### CODE REVIEW

**Comment by chrisant996** [comment]
Thank you, @nikitalita !  I switched the chrisant996 fork to use Detours.

It should be fairly straightforward to backport that into Cmder's fork based on 0.4.9.

Commit a168e86a31a291c66bb7cd97f862d45391516e3f is a squashed commit with all the relevant changes, if someone would like to take a stab at backporting it.

**Comment by chrisant996** [comment]
Since this fork now uses Detours, this PR isn't needed.

**Comment by nikitalita** [comment]
> Thank you, @nikitalita ! I switched the chrisant996 fork to use [Detours](https://github.com/microsoft/detours).
> 
> It should be fairly straightforward to backport that into Cmder's fork based on 0.4.9.
> 
> Commit [a168e86](https://github.com/chrisant996/clink/commit/a168e86a31a291c66bb7cd97f862d45391516e3f) is a squashed commit with all the relevant changes, if someone would like to take a stab at backporting it.

Eh, looking at it, I think our time would be better spent just fixing cmder's scripts to work on your new fork. Do you have any other backwards-compatibility additions you want to make to this fork, or is script compatiblity about where it will be for release?

**Comment by chrisant996** [comment]
I think the compatibility is about as good as it can be.  I'm working on documenting the new API.  I've ported most of the clink powerline scripts, and most of the clink-completions scripts.

Do you know who are good contacts in the cmder team to work with on that?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chrisant996** [comment]
> I think the compatibility is about as good as it can be. I'm working on documenting the new API.

Update:  Good news -- I made some enhancements to the Lua debugger and was able to track down that the main lingering non-compatible part was because of a bug that isn't related to backward compatibility!  One fix fixes two problems -- yay.

It's now looking like I'll be able to get quite a bit more backward compatibility working "out of the box" for people.  If scripts do sophisticated things (esp. relying on undocumented clink internal functions) then there will still be manual edits necessary, but it looks like in most cases I should be able to get scripts to work without modification.

With that said, it's still beneficial to convert scripts to use the new API -- it's cleaner, easier to use, and has more functionality.

**Comment by nikitalita** [comment]
> I think the compatibility is about as good as it can be. I'm working on documenting the new API. I've ported most of the clink powerline scripts, and most of the clink-completions scripts. Do you know who are good contacts in the cmder team to work with on that?

Honestly, it looks like not much of anything is being done on cmder at the moment. I think this is something that's going to have to come from the outside.

**Comment by nikitalita** [comment]
That said, I'll open up an issue about this on cmder and see if I can get one of the devs to comment.

**Comment by chrisant996** [comment]
Ah ok, cool.  Well, last night I got backward compatibility mostly working.  So it's beginning to look like I may be able to get it to be drop-in compatible with cmder.

But it's still worth updating scripts:

- I've found a lot of bugs in the clink-completions scripts that are worth fixing and are easy to fix.
- I've made some enhancements to the powerline scripts.
- The cmder startup for clink is so slow...

So I'll work on those as well.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nikitalita** [comment]
> Ah ok, cool. Well, last night I got backward compatibility mostly working. So it's beginning to look like I may be able to get it to be drop-in compatible with cmder. But it's still worth updating scripts: - I've found a lot of bugs in the clink-completions scripts that are worth fixing and are easy to fix. - I've made some enhancements to the powerline scripts. - The cmder startup for clink is so slow... So I'll work on those as well.

cool; it does look like @daxgames is actively working on stuff on his fork (although it hasn't been merged in yet), so you might want to hit him up

**Pull request closed without merging**
